# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summary_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='summary_api.proto',
  package='summary_statistics',
  syntax='proto3',
  serialized_options=b'Z^github.com/e-conomic/hiring-assignments/machinelearningteam/summary-statistics-service/summary',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11summary_api.proto\x12\x12summary_statistics\"{\n\x18SummarizeDocumentRequest\x12.\n\x08\x64ocument\x18\x01 \x01(\x0b\x32\x1c.summary_statistics.Document\x12\x1e\n\x16params_for_aggregation\x18\x02 \x01(\t\x12\x0f\n\x07\x65xclude\x18\x03 \x01(\t\")\n\x16SummarizeDocumentReply\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"O\n\x08\x44ocument\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x32\n\x06source\x18\x02 \x01(\x0b\x32\".summary_statistics.DocumentSource\"\"\n\x0e\x44ocumentSource\x12\x10\n\x08http_uri\x18\x01 \x01(\t2\x85\x01\n\x12\x44ocumentSummarizer\x12o\n\x11SummarizeDocument\x12,.summary_statistics.SummarizeDocumentRequest\x1a*.summary_statistics.SummarizeDocumentReply\"\x00\x42`Z^github.com/e-conomic/hiring-assignments/machinelearningteam/summary-statistics-service/summaryb\x06proto3'
)




_SUMMARIZEDOCUMENTREQUEST = _descriptor.Descriptor(
  name='SummarizeDocumentRequest',
  full_name='summary_statistics.SummarizeDocumentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='document', full_name='summary_statistics.SummarizeDocumentRequest.document', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params_for_aggregation', full_name='summary_statistics.SummarizeDocumentRequest.params_for_aggregation', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exclude', full_name='summary_statistics.SummarizeDocumentRequest.exclude', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=164,
)


_SUMMARIZEDOCUMENTREPLY = _descriptor.Descriptor(
  name='SummarizeDocumentReply',
  full_name='summary_statistics.SummarizeDocumentReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='summary_statistics.SummarizeDocumentReply.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=207,
)


_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='summary_statistics.Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='summary_statistics.Document.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='summary_statistics.Document.source', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=288,
)


_DOCUMENTSOURCE = _descriptor.Descriptor(
  name='DocumentSource',
  full_name='summary_statistics.DocumentSource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='http_uri', full_name='summary_statistics.DocumentSource.http_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=324,
)

_SUMMARIZEDOCUMENTREQUEST.fields_by_name['document'].message_type = _DOCUMENT
_DOCUMENT.fields_by_name['source'].message_type = _DOCUMENTSOURCE
DESCRIPTOR.message_types_by_name['SummarizeDocumentRequest'] = _SUMMARIZEDOCUMENTREQUEST
DESCRIPTOR.message_types_by_name['SummarizeDocumentReply'] = _SUMMARIZEDOCUMENTREPLY
DESCRIPTOR.message_types_by_name['Document'] = _DOCUMENT
DESCRIPTOR.message_types_by_name['DocumentSource'] = _DOCUMENTSOURCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SummarizeDocumentRequest = _reflection.GeneratedProtocolMessageType('SummarizeDocumentRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARIZEDOCUMENTREQUEST,
  '__module__' : 'summary_api_pb2'
  # @@protoc_insertion_point(class_scope:summary_statistics.SummarizeDocumentRequest)
  })
_sym_db.RegisterMessage(SummarizeDocumentRequest)

SummarizeDocumentReply = _reflection.GeneratedProtocolMessageType('SummarizeDocumentReply', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARIZEDOCUMENTREPLY,
  '__module__' : 'summary_api_pb2'
  # @@protoc_insertion_point(class_scope:summary_statistics.SummarizeDocumentReply)
  })
_sym_db.RegisterMessage(SummarizeDocumentReply)

Document = _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENT,
  '__module__' : 'summary_api_pb2'
  # @@protoc_insertion_point(class_scope:summary_statistics.Document)
  })
_sym_db.RegisterMessage(Document)

DocumentSource = _reflection.GeneratedProtocolMessageType('DocumentSource', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTSOURCE,
  '__module__' : 'summary_api_pb2'
  # @@protoc_insertion_point(class_scope:summary_statistics.DocumentSource)
  })
_sym_db.RegisterMessage(DocumentSource)


DESCRIPTOR._options = None

_DOCUMENTSUMMARIZER = _descriptor.ServiceDescriptor(
  name='DocumentSummarizer',
  full_name='summary_statistics.DocumentSummarizer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=327,
  serialized_end=460,
  methods=[
  _descriptor.MethodDescriptor(
    name='SummarizeDocument',
    full_name='summary_statistics.DocumentSummarizer.SummarizeDocument',
    index=0,
    containing_service=None,
    input_type=_SUMMARIZEDOCUMENTREQUEST,
    output_type=_SUMMARIZEDOCUMENTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOCUMENTSUMMARIZER)

DESCRIPTOR.services_by_name['DocumentSummarizer'] = _DOCUMENTSUMMARIZER

# @@protoc_insertion_point(module_scope)
